FROM ubuntu:18.04
ENV DEBIAN_FRONTEND noninteractive

COPY arm-cross-compile-sources.list /etc/apt/sources.list.d/arm-cross-compile-sources.list
RUN sed -i -e 's/http/[arch=amd64] http/g' /etc/apt/sources.list

RUN dpkg --add-architecture armhf && \
	apt-get -y update && apt-get -y upgrade
RUN apt-get install -y build-essential libtool gcc gcc-arm-linux-gnueabihf g++ make automake autoconf libsndfile-dev:armhf 
